import { clone, scalarFromInput } from '../utils.js';
import { initializeFormValues, normalizeFormPath, validateFormData } from '../services/form-validation.js';
import { t } from '../i18n.js';

const el=(tag,props={},text='')=>{const node=document.createElement(tag);Object.entries(props).forEach(([key,value])=>{if(key==='class')node.className=value;else if(key==='dataset')Object.entries(value).forEach(([name,data])=>node.dataset[name]=data);else if(key in node)node[key]=value;else node.setAttribute(key,value)});if(text)node.textContent=text;return node};
const pathKey=path=>normalizeFormPath(path.map(String).join('.'));
const getAt=(value,path)=>path.reduce((current,key)=>current?.[key],value);
const setAt=(value,path,next)=>{if(!path.length)return next;let target=value;for(let index=0;index<path.length-1;index+=1){const key=path[index];if(target[key]===undefined)target[key]=Number.isInteger(Number(path[index+1]))?[]:{ };target=target[key]}target[path.at(-1)]=next;return value};
const isUuidEligible=(propertyName,schema)=>{if(!schema||schema.type!=='string'||schema.enum)return false;const name=String(propertyName||'');return name.toLowerCase()==='id'||/-id$/i.test(name)||/_id$/i.test(name)||schema.format==='uuid'};
const uuidBytesToString=bytes=>[...bytes].map(byte=>byte.toString(16).padStart(2,'0')).join('').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5');
const generateUuidV4=cryptoObject=>{if(cryptoObject?.randomUUID)return cryptoObject.randomUUID();if(!cryptoObject?.getRandomValues)throw new Error('secure crypto unavailable');const bytes=new Uint8Array(16);cryptoObject.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;return uuidBytesToString(bytes)};

export class FormView{
  constructor(root){this.root=root;this.schema=null;this.values={};this.errors=[];this.onSubmit=null;this.statusKey=null;this.statusKind='';this.renderEmpty()}
  renderEmpty(){this.statusKey=null;this.statusKind='';const status=document.querySelector('#form-status'),help=document.querySelector('.form-help');if(status){status.hidden=true;status.textContent='';status.className='form-status'}if(help)help.hidden=true;const empty=el('div',{class:'form-empty',role:'status','aria-live':'polite'});empty.append(el('p',{class:'form-empty-title'},t('formLoadPrompt')),el('p',{class:'form-empty-help'},t('formScope')));this.root.replaceChildren(empty)}
  setStatus(key,kind=''){this.statusKey=key;this.statusKind=kind;const status=document.querySelector('#form-status');if(status){status.hidden=false;status.textContent=t(key);status.className=`form-status ${kind}`}}
  loadSchema(schema){this.schema=clone(schema);this.values=initializeFormValues(this.schema)||{};this.errors=[];this.setStatus('formLoaded','success');const help=document.querySelector('.form-help');if(help)help.hidden=false;this.render()}
  refreshLanguage(){const active=document.activeElement,focusPath=active?.dataset?.formPath,focusUuid=active?.dataset?.formUuid,summary=document.querySelector('#form-error-summary'),summaryWasOpen=summary?.open,summaryFocused=summary?.contains(active);this.render();if(this.statusKey)this.setStatus(this.statusKey,this.statusKind);const target=focusUuid?this.root.querySelector(`[data-form-uuid="${focusUuid}"]`):focusPath?this.root.querySelector(`[data-form-path="${focusPath}"]`):null;if(target)target.focus();else if(summaryFocused)summary.querySelector('summary')?.focus();if(summaryWasOpen&&summary)summary.open=true}
  render(){if(!this.schema)return this.renderEmpty();this.root.replaceChildren();const fragment=document.createDocumentFragment();fragment.append(this.renderNode(this.schema,[],true,false));this.root.append(fragment);this.renderErrors(this.errors)}
  renderNode(schema,path,root=false,fieldRequired=false){
    if(schema.type==='object'){const group=el(root?'div':'fieldset',{class:`form-group form-depth-${path.length}`,dataset:{formPath:pathKey(path)}});if(!root)group.append(el('legend',{},schema.title||path.at(-1)||t('formObject')));Object.entries(schema.properties||{}).forEach(([key,child])=>group.append(this.renderNode(child,[...path,key],false,(schema.required||[]).includes(key))));return group}
    if(schema.type==='array'){const group=el('fieldset',{class:`form-group form-array form-depth-${path.length}`,dataset:{formPath:pathKey(path)}});group.append(el('legend',{},schema.title||path.at(-1)||t('formArray')));const values=Array.isArray(getAt(this.values,path))?getAt(this.values,path):[];values.forEach((value,index)=>{const itemPath=[...path,index],itemSchema=schema.items||{type:'string'},item=el('div',{class:`form-array-item ${itemSchema.type==='object'||itemSchema.type==='array'?'form-array-complex-item':'form-array-scalar-item'}`,dataset:{formPath:pathKey(itemPath)}}),valueRegion=el('div',{class:'form-array-value'}),actions=el('div',{class:'form-array-item-actions'});valueRegion.append(this.renderNode(itemSchema,itemPath));const remove=el('button',{type:'button',class:'form-array-remove',dataset:{formRemove:pathKey(itemPath)},title:t('formRemoveItem'),'aria-label':t('formRemoveItemLabel',{path:pathKey(itemPath)})},t('formRemoveItem'));actions.append(remove);item.append(valueRegion,actions);group.append(item)});group.append(el('button',{type:'button',class:'form-array-add',dataset:{formAdd:pathKey(path)}},t('formAddItem')));return group}
    const field=el('div',{class:`form-field${schema.type==='boolean'?' boolean-field':''}`,dataset:{formPath:pathKey(path)}}),fieldId=`form-field-${pathKey(path)}`,descriptionId=`form-description-${pathKey(path)}`,errorId=`form-error-${pathKey(path)}`,label=el('label',{for:fieldId},`${schema.title||path.at(-1)||t('formField')}${fieldRequired?' *':''}`),propertyName=typeof path.at(-1)==='string'?path.at(-1):'';let control;
    if(schema.enum){control=el('select',{id:fieldId,dataset:{formPath:pathKey(path)}});control.append(el('option',{value:''},t('formSelectOption')));schema.enum.forEach(option=>control.append(el('option',{value:JSON.stringify(option)},String(option))))}else if(schema.type==='boolean')control=el('input',{id:fieldId,type:'checkbox',class:'vison-checkbox',dataset:{formPath:pathKey(path)}});else if(schema.type==='null')control=el('input',{id:fieldId,type:'text',disabled:true,value:'null',dataset:{formPath:pathKey(path)}});else control=el('input',{id:fieldId,type:schema.type==='number'||schema.type==='integer'?'number':'text',dataset:{formPath:pathKey(path)}});
    const value=getAt(this.values,path);if(control.type==='checkbox')control.checked=value===true;else if(value!==undefined)control.value=schema.enum?JSON.stringify(value):String(value);if(schema.minimum!==undefined)control.min=schema.minimum;if(schema.maximum!==undefined)control.max=schema.maximum;if(schema.minLength!==undefined)control.minLength=schema.minLength;if(schema.maxLength!==undefined)control.maxLength=schema.maxLength;if(schema.pattern)control.pattern=schema.pattern;if(schema.format&&schema.format==='email')control.type='email';const description=schema.description?el('small',{class:'form-description',id:descriptionId},schema.description):null,error=el('p',{class:'form-error',id:errorId,'data-error-for':pathKey(path),hidden:true});control.setAttribute('aria-describedby',[descriptionId,errorId].filter((id,index)=>index===0&&description||index===1).join(' '));const controlRow=el('div',{class:'form-control-row'});controlRow.append(control);if(isUuidEligible(propertyName,schema)){const uuidButton=el('button',{type:'button',class:'form-generate-uuid',dataset:{formUuid:pathKey(path)},title:t('formGenerateUuid'), 'aria-label':t('formGenerateUuidLabel',{field:propertyName})},t('formGenerateUuid'));controlRow.append(uuidButton)}field.append(label,controlRow,error);if(description)field.append(description);return field;
  }
  update(path,control){let value;if(control.type==='checkbox')value=control.checked;else if(control.value==='')value=undefined;else if(control.tagName==='SELECT')value=JSON.parse(control.value);else value=scalarFromInput(control.value,this.schemaAt(path).type);setAt(this.values,path,value);this.clearError(path)}
  schemaAt(path){return path.reduce((node,key)=>node?.type==='array'?node.items:node?.properties?.[key],this.schema)}
  clearError(path){const key=pathKey(path);this.errors=this.errors.filter(error=>normalizeFormPath(error.path)!==key);this.renderErrors(this.errors)}
  validate(){this.errors=validateFormData(this.schema,this.values);this.renderErrors(this.errors);return this.errors}
  renderErrors(errors){const normalized=errors.map(error=>({...error,path:normalizeFormPath(error.path)})),byPath=new Map();normalized.forEach(error=>{const list=byPath.get(error.path)||[];list.push(error);byPath.set(error.path,list)});const summary=document.querySelector('#form-error-summary');if(summary){const wasOpen=summary.open;summary.replaceChildren();summary.hidden=!normalized.length;if(normalized.length){summary.append(el('summary',{class:'form-error-summary-count'},t('formErrorCount',{count:normalized.length})));const details=el('div',{class:'form-error-summary-details'});details.append(el('p',{class:'form-error-summary-help'},t('formErrorSummaryHelp')));const links=el('ul',{class:'form-error-summary-links'});byPath.forEach((fieldErrors,path)=>{const link=el('a',{href:`#form-field-${path}`,class:'form-error-link'},t('formErrorLink',{path}));link.addEventListener('click',event=>{event.preventDefault();const control=document.getElementById(`form-field-${path}`);control?.focus();control?.scrollIntoView({block:'nearest'})});const item=el('li');item.append(link);links.append(item)});details.append(links);summary.append(details);summary.open=wasOpen}else summary.open=false}this.root.querySelectorAll('[data-error-for]').forEach(node=>{const path=normalizeFormPath(node.dataset.errorFor),fieldErrors=byPath.get(path)||[],invalid=fieldErrors.length>0;node.hidden=!invalid;node.textContent=fieldErrors.map(error=>error.message).join(' ');const field=node.closest('.form-field'),control=field?.querySelector('input,select');control?.toggleAttribute('aria-invalid',invalid);field?.classList.toggle('has-error',invalid)})}
  addArray(path){const target=getAt(this.values,path);if(Array.isArray(target)){target.push(initializeFormValues(this.schemaAt(path).items));this.render()}}
  removeArray(path){const parent=getAt(this.values,path.slice(0,-1));if(Array.isArray(parent)){const index=Number(path.at(-1));parent.splice(index,1);this.render();const next=parent[index]!==undefined?index:parent.length-1;const focusTarget=next>=0?this.root.querySelector(`[data-form-remove="${pathKey([...path.slice(0,-1),next])}"]`):this.root.querySelector(`[data-form-add="${pathKey(path.slice(0,-1))}"]`);focusTarget?.focus()}}
  generateUuid(path){const fieldPath=pathKey(path),control=document.getElementById(`form-field-${fieldPath}`),button=this.root.querySelector(`[data-form-uuid="${fieldPath}"]`);if(!control||!button)return false;if(control.value&&!globalThis.confirm?.(t('formUuidConfirm'))){control.focus();return false}try{control.value=generateUuidV4(globalThis.crypto);this.update(path,control);this.setStatus('formUuidGenerated','success');this.root.querySelector(`[data-form-uuid="${fieldPath}"]`)?.focus();return true}catch{this.setStatus('formUuidUnavailable','error');button.focus();return false}}
}

export { generateUuidV4, isUuidEligible };
