export const TYPES = ['object','array','string','number','integer','boolean','null'];
export const SCHEMA_VERSION = 1;
export const uid = () => `n_${Math.random().toString(36).slice(2,9)}${Date.now().toString(36).slice(-3)}`;
export const clone = value => JSON.parse(JSON.stringify(value));
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const prettyJson = value => JSON.stringify(value, null, 2);
export function scalarFromInput(value, type) { if (value === '') return undefined; if (type === 'boolean') return value === 'true'; if (type === 'number' || type === 'integer') return Number(value); if (type === 'null') return null; try { return JSON.parse(value); } catch { return value; } }
export function inferType(schema) { if (schema.properties) return 'object'; if (schema.items) return 'array'; if (schema.enum) return typeof schema.enum[0] === 'number' ? 'number' : 'string'; return 'string'; }
export function normalizeSchema(input) { const source = input && typeof input === 'object' && !Array.isArray(input) ? clone(input) : {}; const normalized = { ...source, schemaVersion: Number(source.schemaVersion) || SCHEMA_VERSION, type: TYPES.includes(source.type) ? source.type : inferType(source) }; if (normalized.type === 'object') normalized.properties = normalized.properties && typeof normalized.properties === 'object' && !Array.isArray(normalized.properties) ? normalized.properties : {}; if (normalized.type === 'array' && normalized.items && typeof normalized.items !== 'object') delete normalized.items; return normalized; }
export function schemaToNodes(schema, name = 'root', parent = null) { schema = normalizeSchema(schema); const node = { id: uid(), name, parent, type: schema.type, description: schema.description || '', required: false, ...schema, children: [] }; delete node.properties; delete node.items; if (node.type === 'object') Object.entries(schema.properties || {}).forEach(([key, child]) => { const c = schemaToNodes(child, key, node.id); c.required = (schema.required || []).includes(key); node.children.push(c); }); else if (node.type === 'array' && schema.items) node.children.push(schemaToNodes(schema.items, 'items', node.id)); return node; }
export function nodesToSchema(node) { const result = { schemaVersion: SCHEMA_VERSION }; const allowed = ['$schema','title','description','default','enum','examples','format','minimum','maximum','minLength','maxLength','pattern']; allowed.forEach(k => { if (node[k] !== undefined && node[k] !== '' && !(Array.isArray(node[k]) && !node[k].length)) result[k] = node[k]; }); result.type = node.type; if (node.type === 'object') { result.properties = {}; const required = []; node.children.filter(c=>c.name !== 'items').forEach(c => { result.properties[c.name || 'property'] = nodesToSchema(c); if (c.required) required.push(c.name || 'property'); }); if (required.length) result.required = required; } if (node.type === 'array') { const item = node.children.find(c => c.name === 'items') || node.children[0]; if (item) result.items = nodesToSchema(item); } return result; }
export function flatten(root, out = []) { out.push(root); root.children.forEach(c => flatten(c,out)); return out; }
export function validateSchema(schema) { const errors = []; if (!schema || typeof schema !== 'object' || Array.isArray(schema)) errors.push('O documento precisa ser um objeto JSON.'); if (!schema?.type) errors.push('O schema raiz precisa declarar um tipo.'); const walk = (n,path='root') => { if (!TYPES.includes(n.type)) errors.push(`${path}: tipo inválido.`); if (n.type === 'object') Object.keys(n.properties || {}).forEach(k => { if (!k.trim()) errors.push(`${path}: há uma propriedade sem nome.`); walk(n.properties[k], `${path}.${k}`); }); if (n.type === 'array' && n.items) walk(n.items, `${path}.items`); if (n.type === 'integer' && n.minimum !== undefined && !Number.isInteger(n.minimum)) errors.push(`${path}: minimum deve ser inteiro.`); if (n.pattern) { try { new RegExp(n.pattern); } catch { errors.push(`${path}: regex inválida.`); } } }; if (!errors.length) walk(schema); return errors; }
